[package]
name = "gnvim"
version = "0.1.0"
authors = ["Ville Hakulinen <ville.hakulinen@gmail.com>"]

[profile.dev]
debug = true

[features]
default = ["webkit"]

unstable = []
webkit = ["webkit2gtk"]

[dependencies]
#neovim-lib = "0.6"
structopt = "0.2"

gio = "0.7"
pango = "0.7"
pangocairo = "0.8"
cairo-rs = "0.7"
glib = "0.8"
gdk = "0.11"
gdk-pixbuf = "0.7"

pulldown-cmark = { version = "0.2", default-features = false }
ammonia = "2"
syntect = "3"
lazy_static = "1.3.0"

[dependencies.gtk]
version = "0.7"
features = ["v3_18"]

[dependencies.webkit2gtk]
version = "0.8"
features = ["v2_14"]
optional = true

[dependencies.neovim-lib]
#git = "https://github.com/vhakulinen/neovim-lib"
git = "https://github.com/daa84/neovim-lib"
